
name: daily_statcast_load

#testing cron schedul
on:
  schedule:
    - cron: '*/11 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install boto3
          pip install pybaseball
          
      - name: Run daily_load script
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_ACCESS_SECRET_ID: ${{ secrets.AWS_ACCESS_SECRET_ID }}
        run:
          python daily_load.py
